QuestionsRT/QuestionsRT/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html"), name='inicio'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('usuarios/', include('usuarios.urls', namespace="gestion_usuarios")),
    path('preguntas/', include('preguntas.urls', namespace="gestion_preguntas")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

QuestionsRT/preguntas/urls.py
from django.conf.urls import url
from .views import ( PreguntaCreateView, PreguntasListView, RespuestaAjax, Resultados)
from django.conf import settings
from django.conf.urls.static import static


app_name = 'preguntas'

urlpatterns = [
    url('crear-pregunta', PreguntaCreateView.as_view(), name='crear_pregunta'),
    url('listar-preguntas', PreguntasListView.as_view(), name='listar_preguntas'),
    url('resultados', Resultados.as_view(), name='resultados'),
    url('respuesta', RespuestaAjax.as_view(), name='respuesta')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

QuestionsRT/usuarios/urls.py
from django.conf.urls import url
from .views import ( LogoutTemplateView, UsuarioCreateView, UsuariosListView)
from django.conf import settings
from django.conf.urls.static import static

app_name = 'usuarios'

urlpatterns = [
    url('crear-usuario', UsuarioCreateView.as_view(), name='crear_usuario'),
    url('listar-usuarios', UsuariosListView.as_view(), name='listar_usuarios'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

QuestionsRT/preguntas/models.py
from django.db import models
from usuarios.models import Usuario

class Pregunta(models.Model):


    respuesta_choices = (
        (0, True),
        (1, False),
    )

    pregunta = models.CharField(verbose_name="Pregunta", max_length=300)
    respuesta = models.BooleanField(verbose_name="Respuesta correcta", choices=respuesta_choices)
    tipo = models.CharField(max_length=70, default="Pregunta de Falso o Verdadero")
    imagen_pregunta = models.ImageField(verbose_name="Imagen de pregunta", upload_to='imagenes_preguntas/', null=True)

    def __str__(self):
        return str(self.pregunta)


class Unica_respuesta(models.Model):
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
    estudiante = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    respuesta = models.TextField()

    def __str__(self):
        return str(self.pregunta)

QuestionsRT/usuarios/models.py
from django.db import models
from django.contrib.auth.models import User

class Usuario(User):

    perfil_usuario = (
        (0, 'Profesor'),
        (1, 'Estudiante'),

    )

    perfil_usuario = models.IntegerField(choices=perfil_usuario, verbose_name="Perfil de usuario", default=0)
    imagen_perfil = models.ImageField(verbose_name="Imagen de perfil", upload_to='imagenes_perfil/', null=True)

QuestionsRT/preguntas/forms.py
from django import forms
from .models import Pregunta

class PreguntaCreateForm(forms.ModelForm):
    class Meta:
        model = Pregunta
        fields = ('pregunta', 'respuesta', 'tipo', 'imagen_pregunta')

QuestionsRT/usuarios/forms.py
from django import forms
from .models import Usuario
from django.contrib.auth.forms import UserCreationForm

password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput(attrs={'maxlength': 30, 'class': 'form-control', 'placeholder': ("Contraseña")})) #Nuevo campo
password2 = forms.CharField(label="Contraseña (confirmación)", widget=forms.PasswordInput(attrs={'maxlength': 30, 'class': 'form-control', 'placeholder': ("Confirma tu contraseña")}))
username = forms.CharField(label="Usuario", widget=forms.TextInput(attrs={'maxlength': 30, 'class': 'form-control', 'placeholder': ("Usuario")}))

class UsuarioCreateForm(UserCreationForm):
    class Meta:
        model = Usuario
        exclude = ('is_active', 'last_login', 'groups', 'user_permissions', 'is_staff', 'date_joined', 'is_superuser',)
        fields = ('username', 'password1', 'password2', 'first_name', 'last_name',
                  'email','perfil_usuario', 'imagen_perfil')

QuestionsRT/preguntas/views.py
from django.views.generic import CreateView
from django.views.generic import ListView, View
from django.http import JsonResponse #Respuestas AJAX

from usuarios.models import Usuario
from .models import Pregunta, Unica_respuesta
from .forms import PreguntaCreateForm

class PreguntaCreateView(CreateView):
    model = Pregunta
    template_name = "preguntas/crearPregunta_form.html"
    form_class = PreguntaCreateForm
    success_msg = "Pregunta creada exitosamente"
    success_url = 'listar-preguntas'


class PreguntasListView(ListView):
    model = Pregunta

    def get_context_data(self, **kwargs):
        context = super(PreguntasListView, self).get_context_data(**kwargs)
        context['count'] = self.get_queryset().count()
        return context

class Resultados(ListView):
    model = Pregunta
    template_name = "preguntas/resultados_list.html"

    def get_context_data(self, **kwargs):
        context = super(Resultados, self).get_context_data(**kwargs)

        preguntas = Pregunta.objects.all()
        respuestas_preguntas = Unica_respuesta.objects.all()
        pregunta_FV = []

        for pre in preguntas:

            respuesta = '0'
            if pre.respuesta:
                respuesta = '1'

            buenas = respuestas_preguntas.filter(pregunta=pre.id, respuesta=respuesta)
            malas = respuestas_preguntas.filter(pregunta=pre.id).exclude(respuesta=respuesta)
            pregunta_FV.append({'pregunta': pre, 'buenas': buenas, 'malas':malas})

        context['count'] = self.get_queryset().count()
        context['pregunta_FV'] = pregunta_FV
        return context


# @class RespuestaAjax: vista manejada con Ajax que permite que los estudiantes
# puedan responder las preguntas que se les realizan en tiempo real

class RespuestaAjax(View):
    def get(self, request, *args, **kwargs):

        pregunta = Pregunta.objects.get(id = request.GET['idPregunta'])
        estudiante = Usuario.objects.get(id = request.GET['idEstudiante'])

        data = {
            'is_taken': Unica_respuesta.objects.filter(estudiante=estudiante, pregunta=pregunta).exists()
        }

        if data['is_taken']:
            data['error_message'] = 'Ya respondio la pregunta'

        else:
            Unica_respuesta.objects.create(
                estudiante=estudiante,
                pregunta=pregunta,
                respuesta=request.GET['respuesta'],
            )
            data['error_message'] = 'Se envio la respuesta exitosamente!!'


        return JsonResponse(data)

QuestionsRT/usuarios/views.py
from django.views.generic import CreateView
from django.views.generic import TemplateView, ListView
from .models import Usuario
from .forms import UsuarioCreateForm

class UsuarioCreateView(CreateView):
    model = Usuario
    template_name = "usuarios/usuario_form.html"
    form_class = UsuarioCreateForm
    success_msg = "Usuario creado exitosamente"
    success_url = 'listar-usuarios'


class UsuariosListView(ListView):
    model = Usuario

    def get_context_data(self, **kwargs):
        context = super(UsuariosListView, self).get_context_data(**kwargs)
        context['count'] = self.get_queryset().count()
        return context


class LogoutTemplateView(TemplateView):
    template_name = "logged_out.html"

QuestionsRT/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load user_tags %}

<html>
<head lang="es">

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <!--=================== Estilos de Terceros ===================-->
    <!-- Bootstrap Core CSS -->

    <link href="{% static 'AdminLTE-2.4.0-rc/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css'' %}" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'jquery-ui-1.12.1.custom/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'jquery-ui-1.12.1.custom/jquery-ui.structure.min.css' %}">
    <!--=================== Estilos propios de todas las paginas ===================-->
    <!--Icono principal de la pagina -->
    <!--<link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}"> -->
    {% block all-css %}
    <!-- Custom CSS -->
    <link href="{% static 'AdminLTE-2.4.0-rc/dist/css/AdminLTE.min.css' %}" rel="stylesheet">
    <link href="{% static 'AdminLTE-2.4.0-rc/dist/css/skins/_all-skins.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'plugins/toastr/toastr.css' %}"/>
    {% endblock %}

    <!--=================== Estilos especificos de cada pagina ===================-->
    {% block specific-css %}
    {% endblock %}

    <!--=================== Titulo ===================-->
    <title>{% block title %}Questions RT{% endblock %}</title>

</head>

<body class="hold-transition">
<div class="wrapper">
    <!-- Main Header -->
    <header class="main-header">
        <!-- Logo -->
        <a class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini">R<b>R</b></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>Questions RT</b></span>
        </a>

        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <!-- Navbar Right Menu -->
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    {% if user.is_authenticated %}
                    <!-- User Account Menu -->
                    <li class="dropdown user user-menu">
                        <!-- Menu Toggle Button -->
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <!-- The user image in the navbar-->
                            <!-- hidden-xs hides the username on small devices so only the image appears. -->
                            <span class="hidden-x">{{ user.get_full_name }}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- The user image in the menu -->
                            <li class="user-header" style="height: 142px !important;">
                                {% if user.usuario.imagen_perfil %}
                                <img alt="image" class="img-circle" width="100px" height="100px"
                                     src="{{user.usuario.imagen_perfil.url}}"/>
                                {% else %}
                                <img alt="image" class="img-circle" width="100px" height="100px"
                                     src="../media/pregunta.jpg"/>
                                {% endif %}
                                <p style="color: black">
                                    {{ user.get_full_name }}
                                </p>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                </div>
                                <div class="pull-left">
                                    <a href="{% url 'logout' %}" class="btn btn-default btn-flat"><span
                                            class="fa fa-sign-out"></span> Cerrar Sesión</a>
                                    {% else %}
                                    <a href="{% url 'login' %}" class="btn btn-default btn-flat"><span
                                            class="fa fa-sign-out"></span> Iniciar sesion</a>
                                    {% endif %}
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <!--<div id="wrapper">-->
    {# =================== Carga la barra de navegacion =================== #}
    {% block navbar %}
    {# ============= default navbar ============== #}
    {% include 'sidebar.html' %}
    {% endblock %}

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                {% block page-title %}Questions Real-Time{% endblock %}
            </h1>
        </section>

        <!-- Main content -->
        <section class="content">
            {# =================== Todo el contenido de la pagina se carga aqui =================== #}
            {% block content %}
            {% endblock %}
        </section>
    </div>


    {# =================== Carga el footer de la pagina =================== #}
    {% block footer %}
    {% include 'footer.html' %}
    {% endblock %}

    {# =================== Carga el footer de la pagina =================== #}
    {% block right-menu %}
    {% include 'control_sidebar.html' %}
    {% endblock %}
</div>


<!--=================== Scripts generales de todas las paginas ===================-->
<!-- jQuery -->
{% block jquery-js %}
<!-- jQuery 2.2.3 -->
<script src="{% static 'AdminLTE-2.4.0-rc/plugins/jQuery/jquery-2.2.3.min.js' %}"></script>
<script src="{% static 'jquery-ui-1.12.1.custom/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/reconnecting-websocket.min.js' %}"></script>

{% endblock %}

{% block custom-js %}
<!-- Bootstrap 3.3.6 -->
<script src="{% static 'AdminLTE-2.4.0-rc/bootstrap/js/bootstrap.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'AdminLTE-2.4.0-rc/dist/js/app.min.js' %}"></script>

<!--Script que permite notificar los mensajes de registro y edicion de todos los actores -->
<script src="{% static 'plugins/toastr/toastr.js' %}"></script>

<script>
    {% for msg in messages %}
    $(document).ready(function () {
        setTimeout(function () {
            toastr.options = {
                "closeButton": true,
                "progressBar": true,
                "positionClass": "toast-bottom-left",
                "showEasing": "swing"
            };
            toastr["{{ msg.tags }}"]("{{msg}}")
        }, 500);
    });
    {% endfor %}

</script>
{% endblock %}

<!--=================== Scripts especificos de cada pagina ===================-->
{% block specific-js %}
{% endblock %}

</body>
</html>

QuestionsRT/templates/base_list.html
{% extends "base.html" %}
{# Load the tag library #}
{% load staticfiles %}
{% load bootstrap3 %}

{% block specific-css %}
    <link href="{% static 'AdminLTE-2.4.0-rc/plugins/datatables/dataTables.bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'AdminLTE-2.4.0-rc/plugins/datatables/extensions/Buttons/buttons.dataTables.min.css' %}" rel="stylesheet">
{% endblock %}

{% block page-title %}{% endblock %}
{% block page-description %}{% endblock %}

{% block content %}
    <div class="box box-info">
        <div class="box-header with-border">
            {% block new_button %} {% endblock %}
        </div>
        <form method="post" class="form-horizontal">
            <div class="box-body">
                {% block content-pre-table %} {% endblock %}
                <table id="lista-data-table" class="table table-striped table-bordered dataTable" cellspacing="0" width="100%">
                    {% block cabecera_tabla %}
                    {% endblock cabecera_tabla %}
                    {% block cuerpo_tabla %}
                    {% endblock cuerpo_tabla %}
                </table>
                {% block content-post-table %} {% endblock %}
            </div>
        </form>
    </div>
    {% block secondary_content %}
    {% endblock secondary_content %}
{% endblock %}
{% block specific-js %}
    <script src="{% static 'AdminLTE-2.4.0-rc/plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'AdminLTE-2.4.0-rc/plugins/datatables/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'AdminLTE-2.4.0-rc/plugins/datatables/extensions/Buttons/buttons.html5.min.js' %}"></script>
    <script src="{% static 'AdminLTE-2.4.0-rc/plugins/datatables/extensions/Buttons/buttons.print.min.js' %}"></script>
    <script src="{% static 'AdminLTE-2.4.0-rc/plugins/datatables/extensions/Buttons/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'AdminLTE-2.4.0-rc/plugins/datatables/extensions/Buttons/jszip.min.js' %}"></script>
    <script src="{% static 'AdminLTE-2.4.0-rc/plugins/datatables/extensions/Buttons/pdfmake.min.js' %}"></script>
    <script src="{% static 'AdminLTE-2.4.0-rc/plugins/datatables/extensions/Buttons/vfs_fonts.js' %}"></script>
    <script>
        $(document).ready(function() {
            $('#lista-data-table').DataTable({
                "dom": 'Bfrtip',
                "buttons": [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ],
                "language": {
                    "decimal": ",",
                    "lengthMenu": "Mostrar _MENU_ filas por página",
                    "zeroRecords": "No se encontraron registros que coincidan con la búsqueda",
                    "info": "Mostrando desde _START_ hasta _END_ de _TOTAL_ registros en total",
                    "infoEmpty": "Información no disponible",
                    "infoFiltered": "(filtrado de _MAX_ registros en total)",
                    "emptyTable":     "No hay datos disponibles en la tabla",
                    "thousands":      ".",
                    "loadingRecords": "Cargando...",
                    "processing":     "Procesando...",
                    "search":         "Filtrar:",
                    "paginate": {
                        "first":      "Primera",
                        "last":       "Última",
                        "next":       "Siguiente",
                        "previous":   "Anterior"
                    },
                    "aria": {
                        "sortAscending":  ": activar para ordernar ascedentemente",
                        "sortDescending": ": activar para ordernar descendentemente"
                    }
                },
                "order": [[ 0, "desc" ]]
            });
        } );
    </script>
{% endblock %}

QuestionsRT/templates/footer.html
<!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">

    </div>
    <!-- Default to the left -->
    <strong>Derechos reservados &copy; 2018 <a href="#">Questions Real Time</a>.</strong>
  </footer>

QuestionsRT/templates/preguntas/pregunta_list.html
{% extends "base_list.html" %}
{# Load the tag library #}
{% load staticfiles %}
{% load bootstrap3 %}
{% load user_tags %}

{% block content %}

<h1 style="text-align: center">Classroom virtual</h1>



{% if request.user|has_group:0%}

<a href="{% url "preguntas:resultados" %}" class="btn btn-success"></i>Resultados</a>

<p>

</p>

<div class="card-wrapper">
    {% for pregunta in object_list %}

    <div class="card card-global card-global-flex" style="width: 18rem;">
        <img class="card-img-top image-card" src="{{pregunta.imagen_pregunta.url}}" alt="Card image cap">
        <div class="card-flex">
            <h5 class="card-title title-FV">{{pregunta.tipo}}</h5>
            <p class="card-text pregunta-title">{{pregunta.pregunta}}</p>
            <button type="button" class="btn btn-primary btn-pregunta" data-toggle="modal" data-id="{{pregunta.id}}"
                    data-target="#myModal4">Evaluar tema
            </button>
        </div>
    </div>

    {% endfor %}

</div>

{% endif %}


{% if request.user|has_group:1%}

<h1 style="color: #61bc61; text-align: center;">
    Aqui Se mostraran las preguntas en tiempo real a los estudiantes
</h1>

<div style="display: flex; justify-content: center;">
 <img src="../media/preguntas.jpg">
</div>



<div id="modal_pregunta">
    <div class="modal inmodal" id="myModal4" tabindex="-1" role="dialog" aria-hidden="true" data-keyboard="false"
         data-backdrop="static">
        <div class="modal-dialog">
            <div class="modal-content animated fadeIn">
                <div class="modal-header">
                    <h1 class="modal-id" hidden>
                    </h1>
                    <i class="fa fa-question-circle modal-icon"></i>
                    <h4 class="modal-tipo">Tipo</h4>
                    <div class="text-left">
                        <h2 class="modal-pregunta">Modal title</h2>
                        <ol class="modal-pregunta-opciones"></ol>
                    </div>
                    <div class="align-left">

                    </div>
                </div>
                <div class="modal-body">

                    <div class="modal-respuestas"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-white cerrar" data-dismiss="modal">Cerrar</button>
                    <button type="button" class="btn btn-primary" onclick="responderPregunta()">Enviar</button>
                </div>
            </div>
        </div>
    </div>
</div>

{% endif %}




{% endblock %}


{% block specific-js %}

<script>

    $(function () {

        /*
            se incluye la misma url creada en el archivo Routing para la respectiva
            conexion de los Websockets con Django
        */

        var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
        var ws_path = ws_scheme + '://' + window.location.host + "/classroom/stream";
        var socket = new ReconnectingWebSocket(ws_path);


        /*
            Se establece la conexion del websocket dentro de la Url
        */

        socket.onopen = function() {
            console.log("Hello everywhere")
        }

        if (socket.readyState == WebSocket.OPEN) socket.onopen();

        /*
            Al dar click en el boton Evaluar tema, este envia el id de la pregunta
            al socket y este es recibido para su respectivo proceso
        */

        $(".btn-pregunta").on('click', function(event){
            var id_pregunta =  $(this).data("id");
            socket.send(id_pregunta);

        });

        /*
            Mensaje en tiempo real que envia el websocket
         */

        socket.onmessage = function (message) {

            var data = JSON.parse(message.data);
            var form;
            var id_pregunta;

            if (data.tipo === "Pregunta de Falso o Verdadero") {
                form = fillContainer(['falso', 'verdadero'], false);
            }

            $('#myModal4 .modal-pregunta').text(data.pregunta);

            if (data['pregunta opciones']) {
                for (var i = 0; i < data['pregunta opciones'].length; i++) {
                    var li = document.createElement('li');
                    li.innerHTML = data['pregunta opciones'][i];
                    $('#myModal4 .modal-pregunta-opciones').append(li);
                }
            }
            $('#myModal4 .modal-id').text(data.id_pregunta);
            $('#myModal4 .modal-tipo').text(data.tipo);//captura id del usuario
            $('#myModal4 .modal-respuestas').html(''); //Limpia modal
            $('#myModal4 .modal-respuestas').append(form); //incluye los datos en el modal
            $('#myModal4').modal("show") //Muestra el modal en tiempo real


            //Funcion que crea el modal

            function fillContainer(opciones, multiple) {
                respuestas = ['a', 'b', 'c', 'd'];
                var form = document.createElement('form');
                form.setAttribute('id', 'respuesta_form')
                var type;
                if (multiple) {
                    type = 'checkbox'
                } else {
                    type = 'radio'
                }
                var radioBtn;
                var div;
                var span;
                var label
                for (var i = 0; i < opciones.length; i++) {
                    div = document.createElement('div');
                    span = document.createElement('span');
                    label = document.createElement('label');
                    label.innerHTML = data[opciones[i]];
                    //span.innerHTML= data[opciones[i]];
                    radioBtn = document.createElement('input');
                    radioBtn.setAttribute('type', type);
                    radioBtn.setAttribute('name', 'respuesta');
                    radioBtn.setAttribute('value', i);
                    div.appendChild(radioBtn);
                    //div.appendChild(span);
                    div.appendChild(label);
                    form.appendChild(div);
                }
                return form;
            }

        };

        socket.onclose = function () {
            console.log("Desconectado");
        }

    });


    function responderPregunta(argument){

            var data = {
                idEstudiante: '{{request.user.id}}',
                idPregunta: $(".modal-id").text(),
                respuesta: $("#respuesta_form input[name='respuesta']:checked").val() //obtiene el valor en JS
            };

            //funcion para mandar los datos al servidor
            $.ajax({
                data: data, //la data que se va enviar
                method: 'get', //metodo
                url: "preguntas/respuesta", //url de la peticion
                dataType: 'json',

                success: function (data) {
                    console.log(data.is_taken);
                    if (data.is_taken){

                    $('#myModal4').modal('hide');
                    toastr.error(data.error_message);
                    }

                    else{
                        $('#myModal4').modal('hide');
                        toastr.success(data.error_message);
                       }
                    },
                error: function (err) {
                    toastr.success('No se envio la respuesta!!');
                }
            })

            idCurso="";
            idEstudiante = "";
            idPregunta = "";
            respuesta = "";
        }

</script>

{% endblock %}

QuestionsRT/templates/sidebar.html
{% load staticfiles %}
{% if user.is_authenticated %}
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar Menu -->
        <ul class="sidebar-menu">
            <li class="header">MENÚ</li>
            <!-- Optionally, you can add icons to the links -->
                <li class="treeview">
                    <a href="#"><i class="fa fa-th-large"></i> <span>Gestión de usuarios</span>
                        <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{% url 'usuarios:crear_usuario' %}">Registrar usuario</a></li>
                        <li><a href="{% url 'usuarios:listar_usuarios' %}">Listar usuarios</a></li>
                    </ul>
                </li>
                <li class="treeview">
                    <a href="#"><i class="fa fa-circle-o"></i> <span>Preguntas</span>
                        <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{% url "gestion_preguntas:crear_pregunta" %}">Registrar preguntas</a></li>
                        <li><a href="{% url "gestion_preguntas:listar_preguntas" %}">Listar preguntas</a></li>
                    </ul>
                </li>
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>

{% endif %}

QuestionsRT/templates/usuarios/usuario_list.html
{% extends "base_list.html" %}
{# Load the tag library #}
{% load staticfiles %}
{% load bootstrap3 %}

{% block page-title %}Listado de Usuarios{% endblock %}
{% block page-description %}Utilice las opciones para gestionar usuarios{% endblock %}

{% block cabecera_tabla %}
<thead>
<tr>
    <td>#</td>
    <td>Nombre</td>
    <td>Apellido</td>
    <td>Email</td>
    <td>Tipo</td>
</tr>

</thead>
{% endblock cabecera_tabla %}
{% block cuerpo_tabla %}
<tbody>
{% if object_list %}
{% for usuario in object_list %}
<tr>
    <td>{{ usuario.id }}</td>
    <td>{{ usuario.first_name }}</td>
    <td>{{ usuario.last_name }}</td>
    <td>{{ usuario.email }}</td>
    {% if usuario.perfil_usuario == 0 %}
    <td>Profesor</td>
    {% else %}
    <td>Estudiante</td>
    {% endif %}
</tr>
{% endfor %}

{% else %}
<h1>No hay registros de Usuarios</h1>
{% endif %}
</tbody>
{% endblock cuerpo_tabla %}

{% block new_button %}
    <a href="{% url "gestion_usuarios:crear_usuario" %}" class="btn btn-success"><i class="fa  fa-plus-circle"></i> Crear Usuario</a>
{% endblock %}